"""
Robust NSE ticker resolution for the Portfolio Risk Scanner.

Ports the proven ticker map + alias engine from the NSE Sentiment Analyzer
(318 stock/ETF entries + 240 company-name aliases). Resolution order:

  1. Exact ticker match (offline, instant)
  2. Exact alias match (company name → ticker)
  3. Company-name reverse lookup (exact + partial contains)
  4. Ticker prefix match
  5. Live Yahoo Finance search fallback (network, cached)

This keeps ticker ↔ name in sync reliably: every resolution returns both the
normalized ticker AND the canonical company name, so the UI never shows a
ticker with a stale or mismatched name.
"""

from __future__ import annotations

import threading

# ─── Canonical NSE ticker → company name map (offline, 318 entries) ───
NSE_TICKERS: dict[str, str] = {
    "AARTIDRUGS": "Aarti Drugs",
    "AARTIIND": "Aarti Industries",
    "AARTIPHARM": "Aarti Pharmalabs",
    "ABB": "ABB India",
    "ABFRL": "Aditya Birla Fashion",
    "ACC": "ACC Ltd",
    "ADANIENT": "Adani Enterprises",
    "ADANIGREEN": "Adani Green Energy",
    "ADANIPORTS": "Adani Ports",
    "ADANIPOWER": "Adani Power",
    "ADANITRANS": "Adani Energy Solutions",
    "AJANTPHARM": "Ajanta Pharma",
    "ALKEM": "Alkem Laboratories",
    "AMARAJABAT": "Amararaja Batteries",
    "AMBUJACEM": "Ambuja Cements",
    "APOLLOHOSP": "Apollo Hospitals",
    "APOLLOTYRE": "Apollo Tyres",
    "ASIANPAINT": "Asian Paints",
    "ASTRAL": "Astral Ltd",
    "AUBANK": "AU Small Finance Bank",
    "AUROPHARMA": "Aurobindo Pharma",
    "AXISBANK": "Axis Bank",
    "BAJAJ-AUTO": "Bajaj Auto",
    "BAJAJHIND": "Bajaj Hindusthan Sugar",
    "BAJAJFINSV": "Bajaj Finserv",
    "BAJFINANCE": "Bajaj Finance",
    "BALKRISIND": "Balkrishna Industries",
    "BALRAMPUR": "Balrampur Chini Mills",
    "BANDHANBNK": "Bandhan Bank",
    "BANKBARODA": "Bank of Baroda",
    "BATAINDIA": "Bata India",
    "BEL": "Bharat Electronics",
    "BERGEPAINT": "Berger Paints",
    "BHARATFORG": "Bharat Forge",
    "BHARTIARTL": "Bharti Airtel",
    "BHEL": "BHEL",
    "BIOCON": "Biocon Ltd",
    "BLUEDART": "Blue Dart Express",
    "BLUESTARCO": "Blue Star",
    "BOSCHLTD": "Bosch India",
    "BPCL": "Bharat Petroleum",
    "BRITANNIA": "Britannia Industries",
    "BSOFT": "Birlasoft",
    "CADILAHC": "Cadila Healthcare",
    "CANBK": "Canara Bank",
    "CENTRALBK": "Central Bank of India",
    "CESC": "CESC Ltd",
    "CHOLAFIN": "Cholamandalam Investment",
    "CIPLA": "Cipla",
    "COALINDIA": "Coal India",
    "COCHINSHIP": "Cochin Shipyard",
    "COFORGE": "Coforge",
    "COLPAL": "Colgate Palmolive",
    "CONCOR": "Container Corp of India",
    "COROMANDEL": "Coromandel International",
    "CRISIL": "CRISIL Ltd",
    "CROMPTON": "Crompton Greaves",
    "CUB": "City Union Bank",
    "CYIENT": "Cyient",
    "DABUR": "Dabur India",
    "DCMSHRIRAM": "DCM Shriram",
    "DEEPAKNTR": "Deepak Nitrite",
    "DHAMPUR": "Dhampur Sugar Mills",
    "DIVISLAB": "Divi's Laboratories",
    "DIXON": "Dixon Technologies",
    "DLF": "DLF Ltd",
    "DMART": "Avenue Supermarts",
    "DRREDDY": "Dr. Reddy's Labs",
    "EICHERMOT": "Eicher Motors",
    "EMAMILTD": "Emami Ltd",
    "ENDURANCE": "Endurance Technologies",
    "ENERGY": "Mirae Asset Energy ETF",
    "ETERNAL": "Eternal Ltd",
    "EQUITASBNK": "Equitas Small Finance Bank",
    "ESCORTS": "Escorts Kubota",
    "EXIDEIND": "Exide Industries",
    "FEDERALBNK": "Federal Bank",
    "FINPIPE": "Supreme Petrochem",
    "FORTIS": "Fortis Healthcare",
    "GAIL": "GAIL India",
    "GLAXO": "GlaxoSmithkline Pharma",
    "GLENMARK": "Glenmark Pharma",
    "GODREJAGRO": "Godrej Agrovet",
    "GODREJCP": "Godrej Consumer Products",
    "GODREJIND": "Godrej Industries",
    "GODREJPROP": "Godrej Properties",
    "GOLDBEES": "Nippon India ETF Gold BeES",
    "GRANULES": "Granules India",
    "GRASIM": "Grasim Industries",
    "GROWW": "Groww Asset Management",
    "GSFC": "Gujarat State Fertilizers",
    "GUJGASLTD": "Gujarat Gas",
    "HAL": "Hindustan Aeronautics",
    "HAVELLS": "Havells India",
    "HCLTECH": "HCL Technologies",
    "HDFCAMC": "HDFC Asset Management",
    "HDFCBANK": "HDFC Bank",
    "HDFCLIFE": "HDFC Life Insurance",
    "HEROMOTOCO": "Hero MotoCorp",
    "HEXAWARE": "Hexaware Technologies",
    "HINDALCO": "Hindalco Industries",
    "HINDPETRO": "Hindustan Petroleum",
    "HINDUNILVR": "Hindustan Unilever",
    "HINDZINC": "Hindustan Zinc",
    "HUDCO": "HUDCO",
    "ICICIBANK": "ICICI Bank",
    "ICICIGI": "ICICI Lombard General Insurance",
    "ICICIPRULI": "ICICI Prudential Life",
    "IDBI": "IDBI Bank",
    "IDEA": "Vodafone Idea",
    "IDFCFIRSTB": "IDFC First Bank",
    "IEX": "Indian Energy Exchange",
    "IGL": "Indraprastha Gas",
    "IIFL": "IIFL Finance",
    "INDIANB": "Indian Bank",
    "INDIGO": "InterGlobe Aviation",
    "INDUSINDBK": "IndusInd Bank",
    "INFY": "Infosys",
    "INOXWIND": "Inox Wind",
    "INTELLECT": "Intellect Design Arena",
    "IOC": "Indian Oil Corp",
    "IPCALAB": "IPCA Laboratories",
    "IRCON": "Ircon International",
    "IRCTC": "IRCTC",
    "IRFC": "IRFC",
    "ITC": "ITC Ltd",
    "J&KBANK": "Jammu & Kashmir Bank",
    "JINDALSTEL": "Jindal Steel & Power",
    "JKCEMENT": "JK Cement",
    "JKLAKSHMI": "JK Lakshmi Cement",
    "JSL": "Jindal Stainless",
    "JSWENERGY": "JSW Energy",
    "JSWSTEEL": "JSW Steel",
    "JUBLFOOD": "Jubilant FoodWorks",
    "KANSAINER": "Kansai Nerolac Paints",
    "KARURVYSYA": "Karur Vysya Bank",
    "KEC": "KEC International",
    "KELLTONTEC": "Kellton Tech",
    "KIRLOSENG": "Kirloskar Oil Engines",
    "KOTAKBANK": "Kotak Mahindra Bank",
    "KPITTECH": "KPIT Technologies",
    "L&TFH": "L&T Finance Holdings",
    "LAURUSLABS": "Laurus Labs",
    "LICHSGFIN": "LIC Housing Finance",
    "LICI": "LIC India",
    "LT": "Larsen & Toubro",
    "LTIM": "LTIMindtree",
    "LTTS": "L&T Technology Services",
    "LUPIN": "Lupin Ltd",
    "M&M": "Mahindra & Mahindra",
    "MAHABANK": "Bank of Maharashtra",
    "MAKEINDIA": "Mirae Asset Manufacturing ETF",
    "MANAPPURAM": "Manappuram Finance",
    "MARICO": "Marico Ltd",
    "MARUTI": "Maruti Suzuki",
    "MAXHEALTH": "Max Healthcare",
    "MAZDOCK": "Mazagon Dock",
    "MCDOWELL-N": "United Spirits",
    "MCX": "MCX",
    "METALETF": "Mirae Asset Metal ETF",
    "METROBRAND": "Metro Brands",
    "MFSL": "Max Financial Services",
    "MGL": "Mahanagar Gas",
    "MIDCAPETF": "Nippon India ETF Midcap 150",
    "MINDACORP": "Minda Corporation",
    "MINDTREE": "Mindtree",
    "MODEFENCE": "Mirae Asset Defence ETF",
    "MOIL": "MOIL Ltd",
    "MOTHERSON": "Motherson Sumi",
    "MPHASIS": "Mphasis",
    "MRF": "MRF Tyres",
    "MUTHOOTFIN": "Muthoot Finance",
    "NATCOPHARM": "Natco Pharma",
    "NATIONALUM": "National Aluminium",
    "NAVINFLUOR": "Navin Fluorine",
    "NBCC": "NBCC India",
    "NCC": "NCC Ltd",
    "NESTLEIND": "Nestlé India",
    "NEXT50IETF": "Nippon India ETF Junior BeES",
    "NHPC": "NHPC Ltd",
    "NIFTYBEES": "Nippon India ETF Nifty 50",
    "NMDC": "NMDC Ltd",
    "NTPC": "NTPC Ltd",
    "OBEROIRLTY": "Oberoi Realty",
    "ONGC": "Oil & Natural Gas Corp",
    "PAGEIND": "Page Industries",
    "PERSISTENT": "Persistent Systems",
    "PFC": "Power Finance Corp",
    "PFIZER": "Pfizer India",
    "PHOENIXLTD": "Phoenix Mills",
    "PIDILITIND": "Pidilite Industries",
    "PIIND": "PI Industries",
    "PNB": "Punjab National Bank",
    "PNBHOUSING": "PNB Housing Finance",
    "POLYCAB": "Polycab India",
    "POWERGRID": "Power Grid Corp",
    "PRAJIND": "Praj Industries",
    "PRESTIGE": "Prestige Estates",
    "PTC": "PTC India",
    "PVRINOX": "PVR INOX",
    "PWL": "PW Lakshmi AI & Tech Fund",
    "QUESS": "Quess Corp",
    "RADICO": "Radico Khaitan",
    "RAILTEL": "Railtel Corp",
    "RALLIS": "Rallis India",
    "RAMCOCEM": "Ramco Cements",
    "RATNAMANI": "Ratnamani Metals",
    "RAYMOND": "Raymond Ltd",
    "RBLBANK": "RBL Bank",
    "RCF": "Rashtriya Chemicals",
    "RECLTD": "REC Ltd",
    "RELIANCE": "Reliance Industries",
    "RITES": "RITES Ltd",
    "RVNL": "RVNL",
    "SAIL": "Steel Authority of India",
    "SANOFI": "Sanofi India",
    "SBILIFE": "SBI Life Insurance",
    "SBIN": "State Bank of India",
    "SCHAEFFLER": "Schaeffler India",
    "SHILPAMED": "Shilpa Medicare",
    "SHREECEM": "Shree Cement",
    "SIEMENS": "Siemens India",
    "SKFINDIA": "SKF India",
    "SOBHA": "Sobha Ltd",
    "SOLARINDS": "Solar Industries",
    "SONACOMS": "Sona BLW Precision",
    "SOUTHBANK": "South Indian Bank",
    "SRF": "SRF Ltd",
    "SRTRANSFIN": "Shriram Transport Finance",
    "STARCEMENT": "Star Cement",
    "STLTECH": "Sterlite Technologies",
    "SUNPHARMA": "Sun Pharmaceutical",
    "SUPREMEIND": "Supreme Industries",
    "SUZLON": "Suzlon Energy",
    "SYMPHONY": "Symphony Ltd",
    "SYNGENE": "Syngene International",
    "TATACHEM": "Tata Chemicals",
    "TATACOMM": "Tata Communications",
    "TATACONSUM": "Tata Consumer",
    "TATAELXSI": "Tata Elxsi",
    "TATAMOTORS": "Tata Motors",
    "TATAPOWER": "Tata Power",
    "TATASTEEL": "Tata Steel",
    "TCI": "Transport Corp of India",
    "TCIEXP": "TCI Express",
    "TCS": "Tata Consultancy Services",
    "TEAMLEASE": "TeamLease Services",
    "TECHM": "Tech Mahindra",
    "THERMAX": "Thermax Ltd",
    "TIMKEN": "Timken India",
    "TITAN": "Titan Company",
    "TORNTPHARM": "Torrent Pharmaceuticals",
    "TORNTPOWER": "Torrent Power",
    "TRENT": "Trent Ltd",
    "TRIDENT": "Trident Ltd",
    "TRIVENI": "Triveni Engineering",
    "TV18BRDCST": "TV18 Broadcast",
    "TVSMOTOR": "TVS Motor Company",
    "UBL": "United Breweries",
    "UCOBANK": "UCO Bank",
    "ULTRACEMCO": "UltraTech Cement",
    "UNIONBANK": "Union Bank of India",
    "UPL": "UPL Ltd",
    "UTIAMC": "UTI Asset Management",
    "VBL": "Varun Beverages",
    "VEDL": "Vedanta Ltd",
    "VMART": "V-Mart Retail",
    "VOLTAS": "Voltas Ltd",
    "VRLLOG": "VRL Logistics",
    "WELCORP": "Welspun Corp",
    "WESTLIFE": "Westlife Foodworld",
    "WIPRO": "Wipro Ltd",
    "YESBANK": "Yes Bank",
    "ZEEL": "Zee Entertainment",
    "ZENSARTECH": "Zensar Technologies",
    "ZYDUSLIFE": "Zydus Lifesciences",
    "ABBOTINDIA": "Abbott India",
    "ALOKINDS": "Alok Industries",
    "APLAPOLLO": "APL Apollo Tubes",
    "ASHOKA": "Ashoka Buildcon",
    "ASTERDM": "Aster DM Healthcare",
    "ATGL": "Adani Total Gas",
    "BANKINDIA": "Bank of India",
    "CARBORUNIV": "Carborundum Universal",
    "CENTURYTEX": "Century Textiles",
    "CUMMINSIND": "Cummins India",
    "DALBHARAT": "Dalmia Bharat",
    "FRONTLINE": "Frontline Business Solutions",
    "GRAPHITE": "Graphite India",
    "GRSE": "Garden Reach Shipbuilders",
    "GSPL": "Gujarat State Petronet",
    "GUJALKALI": "Gujarat Alkalies",
    "GUJFLUORO": "Gujarat Fluorochemicals",
    "HERITGEFOOD": "Heritage Foods",
    "HGINFRA": "HG Infra Engineering",
    "HTMEDIA": "HT Media",
    "JBCHEPHARM": "JB Chemicals & Pharmaceuticals",
    "JMC": "JMC Projects",
    "JYOTHYLAB": "Jyothy Labs",
    "LTFOODS": "LT Foods",
    "MAHLIFE": "Mahindra Lifespace Developers",
    "MAHLOG": "Mahindra Logistics",
    "MAHSEAMLES": "Maharashtra Seamless",
    "MOTHERDAIRY": "Mother Dairy Fruit & Vegetable",
    "NIACL": "New India Assurance Company",
    "NIITTECH": "NIIT Technologies",
    "OFSS": "Oracle Financial Services Software",
    "OIL": "Oil India",
    "PNCINFRA": "PNC Infratech",
    "SHOPERSTOP": "Shoppers Stop",
    "SIGNATURE": "Signature Global",
    "SONATSOFTW": "Sonata Software",
    "STARHEALTH": "Star Health and Allied Insurance",
    "SUNTV": "Sun TV Network",
    "TMCV": "Tata Motors CV",
    "TMPV": "Tata Motors Passenger Vehicles",
}

# ─── Company-name / abbreviation aliases → ticker ───
ALIASES: dict[str, str] = {
    "HCL TECH": "HCLTECH",
    "HCL TECHNOLOGIES": "HCLTECH",
    "HDFC": "HDFCBANK",
    "SBI": "SBIN",
    "STATE BANK": "SBIN",
    "HINDUSTAN UNILEVER": "HINDUNILVR",
    "LARSEN": "LT",
    "DMART": "DMART",
    "HERO": "HEROMOTOCO",
    "HERO HONDA": "HEROMOTOCO",
    "DIVI": "DIVISLAB",
    "JSW STEEL": "JSWSTEEL",
    "TATA STEEL": "TATASTEEL",
    "TATA CONSUMER": "TATACONSUM",
    "AIRTEL": "BHARTIARTL",
    "MARUTI SUZUKI": "MARUTI",
    "TECH MAHINDRA": "TECHM",
    "INDUSIND": "INDUSINDBK",
    "POWER GRID": "POWERGRID",
    "SUN PHARMA": "SUNPHARMA",
    "DR. REDDY": "DRREDDY",
    "BAJAJ FINANCE": "BAJFINANCE",
    "ADANI ENTERPRISES": "ADANIENT",
    "ADANI PORTS": "ADANIPORTS",
    "ADANI GREEN": "ADANIGREEN",
    "ADANI POWER": "ADANIPOWER",
    "ADANI TRANS": "ADANITRANS",
    "ULTRATECH": "ULTRACEMCO",
    "ASIAN PAINTS": "ASIANPAINT",
    "APOLLO HOSPITALS": "APOLLOHOSP",
    "APOLLO": "APOLLOHOSP",
    "TORRENT PHARMA": "TORNTPHARM",
    "JUBILANT": "JUBLFOOD",
    "TVS": "TVSMOTOR",
    "VARUN BEVERAGES": "VBL",
    "YES BANK": "YESBANK",
    "BANK OF BARODA": "BANKBARODA",
    "MAHINDRA": "M&M",
    "BHARAT PETROLEUM": "BPCL",
    "HINDUSTAN AERONAUTICS": "HAL",
    "BHARAT ELECTRONICS": "BEL",
    "POWER FINANCE": "PFC",
    "SOLAR INDUSTRIES": "SOLARINDS",
    "BALKRISHNA": "BALKRISIND",
    "PW LAKSHMI": "PWL",
    "VEDANTA": "VEDL",
    "REC": "RECLTD",
    "Pidilite": "PIDILITIND",
    "HAVELLS": "HAVELLS",
    "SIEMENS": "SIEMENS",
    "POLYCAB": "POLYCAB",
    "DIXON": "DIXON",
    "ASTRAL": "ASTRAL",
    "IDFC": "IDFCFIRSTB",
    "MARICO": "MARICO",
    "DABUR": "DABUR",
    "GODREJ": "GODREJCP",
    "CIPLA": "CIPLA",
    "LUPIN": "LUPIN",
    "BIOCON": "BIOCON",
    "BAJAJ HINDUSTHAN": "BAJAJHIND",
    "BALRAMPUR CHINI": "BALRAMPUR",
    "DHAMPUR SUGAR": "DHAMPUR",
    "TRIVENI ENGINEERING": "TRIVENI",
    "DCM SHRIRAM": "DCMSHRIRAM",
    "HDFC BANK": "HDFCBANK",
    "HDFC LTD": "HDFCBANK",
    "HDFC LIMITED": "HDFCBANK",
    "HDFC CORP": "HDFCBANK",
    "ICICI": "ICICIBANK",
    "ICICI BANK": "ICICIBANK",
    "KOTAK": "KOTAKBANK",
    "KOTAK MAHINDRA": "KOTAKBANK",
    "AXIS": "AXISBANK",
    "INDUSIND BANK": "INDUSINDBK",
    "BANK OF INDIA": "BANKINDIA",
    "CANARA": "CANBK",
    "CANARA BANK": "CANBK",
    "PUNJAB NATIONAL": "PNB",
    "UNION BANK": "UNIONBANK",
    "ALLAHABAD BANK": "INDIANB",
    "INDIAN BANK": "INDIANB",
    "MAHARASHTRA BANK": "MAHABANK",
    "BANK OF MAHARASHTRA": "MAHABANK",
    "FEDERAL": "FEDERALBNK",
    "FEDERAL BANK": "FEDERALBNK",
    "SOUTH INDIAN BANK": "SOUTHBANK",
    "RBL": "RBLBANK",
    "BANDHAN": "BANDHANBNK",
    "BANDHAN BANK": "BANDHANBNK",
    "AU BANK": "AUBANK",
    "AU SMALL FINANCE": "AUBANK",
    "CITY UNION": "CUB",
    "KARUR": "KARURVYSYA",
    "KARUR VYSYA": "KARURVYSYA",
    "IDBI": "IDBI",
    "JAMMU KASHMIR BANK": "J&KBANK",
    "J AND K BANK": "J&KBANK",
    "UCO": "UCOBANK",
    "EQUITAS": "EQUITASBNK",
    "EQUITAS BANK": "EQUITASBNK",
    "CENTRAL BANK": "CENTRALBK",
    "SBI LIFE": "SBILIFE",
    "SBI LIFE INSURANCE": "SBILIFE",
    "HDFC LIFE": "HDFCLIFE",
    "HDFC LIFE INSURANCE": "HDFCLIFE",
    "ICICI PRUDENTIAL": "ICICIPRULI",
    "ICICI LOMBARD": "ICICIGI",
    "ICICI GENERAL": "ICICIGI",
    "HDFC AMC": "HDFCAMC",
    "HDFC ASSET MANAGEMENT": "HDFCAMC",
    "UTI AMC": "UTIAMC",
    "SHRIRAM TRANSPORT": "SRTRANSFIN",
    "SHRIRAM FINANCE": "SRTRANSFIN",
    "CHOLA": "CHOLAFIN",
    "CHOLAMANDALAM": "CHOLAFIN",
    "MUTHOOT": "MUTHOOTFIN",
    "MUTHOOT FINANCE": "MUTHOOTFIN",
    "MANAPPURAM": "MANAPPURAM",
    "PNB HOUSING": "PNBHOUSING",
    "LT FINANCE": "L&TFH",
    "LIC HOUSING": "LICHSGFIN",
    "MAX LIFE": "MFSL",
    "MAX FINANCIAL": "MFSL",
    "STAR HEALTH": "STARHEALTH",
    "STAR HEALTH INSURANCE": "STARHEALTH",
    "NEW INDIA ASSURANCE": "NIACL",
    "HCL": "HCLTECH",
    "INFOSYS": "INFY",
    "TATA CONSULTANCY": "TCS",
    "WIPRO": "WIPRO",
    "LTI": "LTIM",
    "LTI MIND TREE": "LTIM",
    "LTIMINDTREE": "LTIM",
    "MIND TREE": "MINDTREE",
    "COFORGE": "COFORGE",
    "PERSISTENT": "PERSISTENT",
    "PERSISTENT SYSTEMS": "PERSISTENT",
    "MPHASIS": "MPHASIS",
    "BIRLASOFT": "BSOFT",
    "KPIT": "KPITTECH",
    "K PIT TECH": "KPITTECH",
    "LT TECHNOLOGY": "LTTS",
    "L&T TECHNOLOGY": "LTTS",
    "TATA ELXSI": "TATAELXSI",
    "ZENSAR": "ZENSARTECH",
    "HEXAWARE": "HEXAWARE",
    "CYIENT": "CYIENT",
    "INTELLECT DESIGN": "INTELLECT",
    "TATA COMMUNICATIONS": "TATACOMM",
    "VODAFONE IDEA": "IDEA",
    "BHARTI": "BHARTIARTL",
    "SONATA": "SONATSOFTW",
    "SONATA SOFTWARE": "SONATSOFTW",
    "NIIT TECH": "NIITTECH",
    "ORACLE FIN": "OFSS",
    "ORACLE FINANCIAL": "OFSS",
    "TECHM": "TECHM",
    "DR REDDYS": "DRREDDY",
    "DR REDDY": "DRREDDY",
    "DIVIS": "DIVISLAB",
    "DIVI LAB": "DIVISLAB",
    "AUROBINDO": "AUROPHARMA",
    "AUROBINDO PHARMA": "AUROPHARMA",
    "CADILA": "CADILAHC",
    "ZYDUS": "ZYDUSLIFE",
    "ZYDUS LIFESCIENCES": "ZYDUSLIFE",
    "ALKEM": "ALKEM",
    "ALKEM LABS": "ALKEM",
    "GLENMARK": "GLENMARK",
    "NATCO": "NATCOPHARM",
    "NATCO PHARMA": "NATCOPHARM",
    "LAURUS": "LAURUSLABS",
    "LAURUS LABS": "LAURUSLABS",
    "IPCA": "IPCALAB",
    "GRANULES": "GRANULES",
    "GRANULES INDIA": "GRANULES",
    "AJANTA": "AJANTPHARM",
    "AJANTA PHARMA": "AJANTPHARM",
    "SHILPA": "SHILPAMED",
    "SHILPA MEDICARE": "SHILPAMED",
    "FORTIS HEALTHCARE": "FORTIS",
    "MAX HEALTHCARE": "MAXHEALTH",
    "MAX HOSPITAL": "MAXHEALTH",
    "APOLLO HOSPITAL": "APOLLOHOSP",
    "GLAXO": "GLAXO",
    "GLAXOSMITHKLINE": "GLAXO",
    "GLAXO INDIA": "GLAXO",
    "SANOFI": "SANOFI",
    "SANOFI INDIA": "SANOFI",
    "PFIZER": "PFIZER",
    "ABBOTT": "ABBOTINDIA",
    "ABBOTT INDIA": "ABBOTINDIA",
    "SYNGENE": "SYNGENE",
    "ASTER DM": "ASTERDM",
    "J B CHEMICALS": "JBCHEPHARM",
    "JB CHEMICALS": "JBCHEPHARM",
    "JYOTHY LABS": "JYOTHYLAB",
    "JYOTHY LABORATORIES": "JYOTHYLAB",
    "HALDIRAM": "HALDIRAM",
    "HALDIRAM FOOD": "HALDIRAM",
    "HERITAGE FOODS": "HERITGEFOOD",
    "TATA MOTOR": "TATAMOTORS",
    "MAHINDRA AND MAHINDRA": "M&M",
    "M AND M": "M&M",
    "MAHINDRA AUTO": "M&M",
    "BAJAJ AUTO": "BAJAJ-AUTO",
    "EICHER": "EICHERMOT",
    "HERO MOTOCORP": "HEROMOTOCO",
    "TVS MOTOR": "TVSMOTOR",
    "APOLLO TYRE": "APOLLOTYRE",
    "APOLLO TYRES": "APOLLOTYRE",
    "MRF TYRES": "MRF",
    "MRF": "MRF",
    "BOSCH": "BOSCHLTD",
    "BHARAT FORGE": "BHARATFORG",
    "EXIDE": "EXIDEIND",
    "EXIDE INDUSTRIES": "EXIDEIND",
    "AMARAJA": "AMARAJABAT",
    "AMAR RAJA": "AMARAJABAT",
    "AMARAJABAT": "AMARAJABAT",
    "SONA BLW": "SONACOMS",
    "MOTHERSON": "MOTHERSON",
    "MOTHERSUMI": "MOTHERSON",
    "MOTHER SUMI": "MOTHERSON",
    "SAMVARDHANA MOTHERSON": "MOTHERSON",
    "ESCORTS": "ESCORTS",
    "ESCORTS KUBOTA": "ESCORTS",
    "ENDURANCE TECH": "ENDURANCE",
    "BALKRISHNA INDUSTRIES": "BALKRISIND",
    "HUL": "HINDUNILVR",
    "HIND UNILEVER": "HINDUNILVR",
    "NESTLE": "NESTLEIND",
    "BRITANNIA": "BRITANNIA",
    "DABUR INDIA": "DABUR",
    "GODREJ CONSUMER": "GODREJCP",
    "COLGATE": "COLPAL",
    "COLPAL": "COLPAL",
    "EMAMI": "EMAMILTD",
    "BATA": "BATAINDIA",
    "BATA INDIA": "BATAINDIA",
    "PAGE INDUSTRIES": "PAGEIND",
    "ADITYA BIRLA FASHION": "ABFRL",
    "ABFRL": "ABFRL",
    "PANTALOONS": "ABFRL",
    "METRO BRAND": "METROBRAND",
    "VMART": "VMART",
    "V MART": "VMART",
    "WESTLIFE": "WESTLIFE",
    "WESTLIFE FOOD": "WESTLIFE",
    "UNITED SPIRITS": "MCDOWELL-N",
    "MCDOWELL": "MCDOWELL-N",
    "UNITED BREWERIES": "UBL",
    "RADICO": "RADICO",
    "RADICO KHAITAN": "RADICO",
    "TRENT": "TRENT",
    "AVENUE SUPERMARTS": "DMART",
    "TATA TEA": "TATACONSUM",
    "TATA COFFEE": "TATACONSUM",
    "JUBILANT FOOD": "JUBLFOOD",
    "KRBL": "KRBL",
    "KRBL LTD": "KRBL",
    "MOTHER DAIRY": "MOTHERDAIRY",
    "CAMPUS": "CAMPUS",
    "CAMPUS ACTIVEWEAR": "CAMPUS",
    "SHOPPER STOP": "SHOPERSTOP",
    "SHOPPERS STOP": "SHOPERSTOP",
    "TATA CHEMICALS": "TATACHEM",
    "OIL AND NATURAL GAS": "ONGC",
    "INDIAN OIL": "IOC",
    "HINDUSTAN PETROLEUM": "HINDPETRO",
    "HPCL": "HINDPETRO",
    "GAIL": "GAIL",
    "GUJARAT GAS": "GUJGASLTD",
    "IGL": "IGL",
    "INDRAPRASTHA GAS": "IGL",
    "MAHANAGAR GAS": "MGL",
    "MGL GAS": "MGL",
    "COAL INDIA": "COALINDIA",
    "JSW ENERGY": "JSWENERGY",
    "TORRENT POWER": "TORNTPOWER",
    "SUZLON": "SUZLON",
    "SUZLON ENERGY": "SUZLON",
    "INOX WIND": "INOXWIND",
    "ADANI TOTAL GAS": "ATGL",
    "ADANI GAS": "ATGL",
    "PETRONET": "PETRONET",
    "PETRONET LNG": "PETRONET",
    "OIL INDIA": "OIL",
    "OIL INDIA LTD": "OIL",
    "JINDAL STEEL": "JINDALSTEL",
    "JINDAL": "JINDALSTEL",
    "STEEL AUTHORITY": "SAIL",
    "NATIONAL ALUMINIUM": "NATIONALUM",
    "NALCO": "NATIONALUM",
    "HINDUSTAN ZINC": "HINDZINC",
    "RATNAMANI": "RATNAMANI",
    "RATNAMANI METAL": "RATNAMANI",
    "WELSPUN": "WELCORP",
    "WELSPUN CORP": "WELCORP",
    "JINDAL STAINLESS": "JSL",
    "JSL": "JSL",
    "MAHARASHTRA SEAMLESS": "MAHSEAMLES",
    "MAHINDRA METAL": "MAHSEAMLES",
    "APL APOLLO": "APLAPOLLO",
    "APL APOLLO TUBES": "APLAPOLLO",
    "ULTRA TECH": "ULTRACEMCO",
    "AMBUJA": "AMBUJACEM",
    "AMBUJA CEMENT": "AMBUJACEM",
    "SHREE CEMENT": "SHREECEM",
    "RAMCO CEMENT": "RAMCOCEM",
    "JK CEMENT": "JKCEMENT",
    "JK LAKSHMI": "JKLAKSHMI",
    "JK LAKSHMI CEMENT": "JKLAKSHMI",
    "STAR CEMENT": "STARCEMENT",
    "BERGER": "BERGEPAINT",
    "BERGER PAINTS": "BERGEPAINT",
    "KANSAI": "KANSAINER",
    "NEROLAC": "KANSAINER",
    "SUPREME INDUSTRIES": "SUPREMEIND",
    "ASTRAL PIPES": "ASTRAL",
    "HEIDELBERG": "HEIDELBERG",
    "HEIDELBERG CEMENT": "HEIDELBERG",
    "DALMIA BHARAT": "DALBHARAT",
    "DALMIA CEMENT": "DALBHARAT",
    "BHARAT HEAVY": "BHEL",
    "BHEL": "BHEL",
    "KIRLOSKAR OIL": "KIRLOSENG",
    "BLUE STAR": "BLUESTARCO",
    "CROMPTON GREAVES": "CROMPTON",
    "PRAJ": "PRAJIND",
    "PRAJ INDUSTRIES": "PRAJIND",
    "KEC INTERNATIONAL": "KEC",
    "SKF": "SKFINDIA",
    "CUMMINS": "CUMMINSIND",
    "CARBORUNDUM": "CARBORUNIV",
    "CARBORUNDUM UNIVERSAL": "CARBORUNIV",
    "GRAPHITE INDIA": "GRAPHITE",
    "PIDILITE": "PIDILITIND",
    "SRF": "SRF",
    "DEEPAK NITRITE": "DEEPAKNTR",
    "NAVIN FLUORINE": "NAVINFLUOR",
    "AARTI": "AARTIIND",
    "AARTI INDUSTRIES": "AARTIIND",
    "AARTI DRUGS": "AARTIDRUGS",
    "AARTI PHARMA": "AARTIPHARM",
    "PI INDUSTRIES": "PIIND",
    "GUJARAT STATE FERT": "GSFC",
    "GSFC": "GSFC",
    "UPL": "UPL",
    "RALLIS": "RALLIS",
    "RCF": "RCF",
    "RASHTRIYA CHEMICAL": "RCF",
    "COROMANDEL": "COROMANDEL",
    "COROMANDEL INTERNATIONAL": "COROMANDEL",
    "GUJARAT STATE PETRO": "GSPL",
    "GUJARAT ALKALIES": "GUJALKALI",
    "GUJARAT FLUORO": "GUJFLUORO",
    "GUJARAT FLUOROCHEMICALS": "GUJFLUORO",
    "LARSEN AND TOUBRO": "LT",
    "L AND T": "LT",
    "L&T": "LT",
    "OBEROI": "OBEROIRLTY",
    "OBEROI REALTY": "OBEROIRLTY",
    "GODREJ PROPERTIES": "GODREJPROP",
    "GODREJ PROPERTY": "GODREJPROP",
    "PRESTIGE ESTATES": "PRESTIGE",
    "SOBHA": "SOBHA",
    "SOBHA LTD": "SOBHA",
    "PHOENIX MILLS": "PHOENIXLTD",
    "CONTAINER CORP": "CONCOR",
    "CONCOR": "CONCOR",
    "RAIL VIKAS": "RVNL",
    "INDIAN RAILWAYS FINANCE": "IRFC",
    "INDIAN RAILWAY CATERING": "IRCTC",
    "L AND T FINANCE": "L&TFH",
    "MAHINDRA LIFESPACE": "MAHLIFE",
    "MAHINDRA LIFESPACES": "MAHLIFE",
    "SUNTECK": "SUNTECK",
    "SUNTEK REALTY": "SUNTECK",
    "SIGNATURE GLOBAL": "SIGNATURE",
    "BRIGADE": "BRIGADE",
    "BRIGADE ENTERPRISES": "BRIGADE",
    "PNC INFRA": "PNCINFRA",
    "PNC INFRASTRUCTURE": "PNCINFRA",
    "ASHOKA BUILD": "ASHOKA",
    "ASHOKA BUILDCON": "ASHOKA",
    "JMC PROJECTS": "JMC",
    "HG INFRA": "HGINFRA",
    "MAZAGON": "MAZDOCK",
    "MAZAGON DOCK": "MAZDOCK",
    "COCHIN SHIP": "COCHINSHIP",
    "COCHIN SHIPYARD": "COCHINSHIP",
    "GARDEN REACH": "GRSE",
    "SHIP BUILDING": "GRSE",
    "ZEE": "ZEEL",
    "ZEE ENTERTAINMENT": "ZEEL",
    "PVR": "PVRINOX",
    "PVR INOX": "PVRINOX",
    "TV18": "TV18BRDCST",
    "STERLITE TECH": "STLTECH",
    "SUN TV": "SUNTV",
    "SUN TV NETWORK": "SUNTV",
    "NETWORK 18": "NETWORK18",
    "NETWORK18": "NETWORK18",
    "HMVL": "HMVL",
    "HT MEDIA": "HTMEDIA",
    "TRANSPORT CORP": "TCI",
    "TCI": "TCI",
    "TCI EXPRESS": "TCIEXP",
    "VRL LOGISTICS": "VRLLOG",
    "BLUE DART": "BLUEDART",
    "ALL CARGO": "ALLCARGO",
    "ALLCARGO": "ALLCARGO",
    "MAHINDRA LOGISTIC": "MAHLOG",
    "MAHINDRA LOGISTICS": "MAHLOG",
    "DELHIVERY": "DELHIVERY",
    "DELIVERY": "ETERNAL",
    "TRIDENT": "TRIDENT",
    "TRIDENT LTD": "TRIDENT",
    "VARDHMAN": "VARDHMAN",
    "VARDHMAN TEXTILES": "VARDHMAN",
    "ALOK INDUSTRIES": "ALOKINDS",
    "CENTURY TEXTILE": "CENTURYTEX",
    "CENTURY": "CENTURYTEX",
    "GODREJ INDUSTRIES": "GODREJIND",
    "GODREJ AGROVET": "GODREJAGRO",
    "CRISIL": "CRISIL",
    "MCX": "MCX",
    "MULTI COMMODITY": "MCX",
    "MFSL": "MFSL",
    "SCHAEFFLER": "SCHAEFFLER",
    "MINDACORP": "MINDACORP",
    "SYMPHONY": "SYMPHONY",
    "QUESS": "QUESS",
    "TEAMLEASE": "TEAMLEASE",
    "LT FOODS": "LTFOODS",
    "LT OVERSEAS": "LTFOODS",
    "BEML": "BEML",
    "BEML LTD": "BEML",
    "NIFTY BEES": "NIFTYBEES",
    "GOLD BEES": "GOLDBEES",
    "JUNIOR BEES": "NEXT50IETF",
    "NEXT 50": "NEXT50IETF",
    "MIDCAP 150": "MIDCAPETF",
    "MID CAP ETF": "MIDCAPETF",
    "DEFENCE ETF": "MODEFENCE",
    "MANUFACTURING ETF": "MAKEINDIA",
    "ENERGY ETF": "ENERGY",
    "METAL ETF": "METALETF",
    "LAKSHMI AI": "PWL",
    "GROWW": "GROWW",
    "ZOMATO": "ETERNAL",
    "ZOMATO LIMITED": "ETERNAL",
    "TATA MOTORS": "TMPV",
    "TATA MOTORS LIMITED": "TMPV",
    "TATA MOTORS PASSENGER": "TMPV",
    "TATA MOTORS CV": "TMCV",
    "TATA MOTORS COMMERCIAL": "TMCV",
    "BAJAJ FINSERV": "BAJAJFINSV",
    "ADANI ENERGY": "ADANITRANS",
    "ADANI ENERGY SOLUTIONS": "ADANITRANS",
    "FRONT LINE": "FRONTLINE",
    "MOTHERSON SUMI": "MOTHERSON",
    "SAMVARDHANA": "MOTHERSON",
}

# Precompute reverse ALIASES (uppercased name → ticker) for fast input resolution
_ALIAS_LOOKUP: dict[str, str] = {}
for _ak, _at in ALIASES.items():
    _alias_upper = _ak.strip().upper()
    if _alias_upper not in _ALIAS_LOOKUP:
        _ALIAS_LOOKUP[_alias_upper] = _at

# In-memory cache for online lookups (avoids repeated network calls)
_online_ticker_cache: dict[str, tuple[str | None, str | None]] = {}
_online_cache_lock = threading.Lock()
_MAX_ONLINE_CACHE = 500


def _search_yahoo_finance(query: str) -> tuple[str | None, str | None]:
    """Search Yahoo Finance REST API for NSE ticker. Fast (~200ms)."""
    try:
        import requests

        url = (
            "https://query2.finance.yahoo.com/v1/finance/search?q="
            f"{requests.utils.quote(query)}&quotesCount=10&newsCount=0"
        )
        r = requests.get(url, headers={"User-Agent": "Mozilla/5.0"}, timeout=3)
        if r.status_code != 200:
            return None, None
        data = r.json()
        quotes = data.get("quotes", [])
        for q_item in quotes:
            sym = q_item.get("symbol", "")
            exch = q_item.get("exchange", "")
            if exch == "NSI" and sym.endswith(".NS"):
                return sym.replace(".NS", ""), q_item.get("shortname", query)
        for q_item in quotes:
            sym = q_item.get("symbol", "")
            if sym.endswith(".NS"):
                return sym.replace(".NS", ""), q_item.get("shortname", query)
    except Exception:
        pass
    return None, None


def _search_ticker_online(query: str) -> tuple[str | None, str | None]:
    """Search for NSE ticker by company name using Yahoo Finance REST API.

    Returns (ticker, name) or (None, None). Cached in-memory.
    """
    q = query.strip()
    if not q or len(q) < 2:
        return None, None
    q_upper = q.upper()
    with _online_cache_lock:
        cached = _online_ticker_cache.get(q_upper)
        if cached is not None:
            return cached
    result = _search_yahoo_finance(q)
    with _online_cache_lock:
        if len(_online_ticker_cache) < _MAX_ONLINE_CACHE:
            _online_ticker_cache[q_upper] = result
    return result


def resolve_ticker(raw_input: str) -> tuple[str | None, str | None]:
    """Resolve user input to a valid NSE ticker symbol + company name.

    Handles tickers, company names, aliases, and partial matches.
    Returns (ticker, company_name) or (None, None) if unresolved.

    Resolution order (fast → slow):
      1. Exact NSE_TICKERS match
      2. Exact ALIASES match (e.g. "HDFC BANK" → "HDFCBANK")
      3. Company name reverse lookup (exact + partial contains)
      4. Ticker prefix match
      5. Yahoo Finance search fallback (network, ~200ms, cached)
    """
    if not raw_input or not raw_input.strip():
        return None, None
    q = raw_input.strip().upper().replace(".NS", "").replace(".BO", "")
    # 1. Exact ticker symbol match
    if q in NSE_TICKERS:
        return q, NSE_TICKERS[q]
    # 2. Exact alias match
    if q in _ALIAS_LOOKUP:
        ticker = _ALIAS_LOOKUP[q]
        return ticker, NSE_TICKERS.get(ticker, ticker)
    # 3. Company name reverse lookup — exact then partial
    for sym, name in NSE_TICKERS.items():
        if name.upper() == q:
            return sym, name
    for sym, name in NSE_TICKERS.items():
        if q in name.upper():
            return sym, name
    # 4. Ticker prefix match
    for sym, name in NSE_TICKERS.items():
        if sym.startswith(q):
            return sym, name
    # 5. Online fallback — Yahoo Finance search
    online_result = _search_ticker_online(raw_input.strip())
    if online_result and online_result[0]:
        ticker, name = online_result
        if ticker in NSE_TICKERS:
            return ticker, NSE_TICKERS[ticker]
        return ticker, name
    return None, None


def get_company_name(ticker: str) -> str:
    """Return the canonical company name for a ticker.

    Resolution: offline map → live Yahoo lookup → sector hint → raw ticker.
    Never returns an empty string.
    """
    clean = ticker.replace(".NS", "").strip().upper()
    if clean in NSE_TICKERS:
        return NSE_TICKERS[clean]
    # Live fallback
    result = _search_ticker_online(clean)
    if result and result[0]:
        return result[1] or clean
    return clean


def build_ticker_options() -> list[str]:
    """Build sorted 'TICKER — Company Name' options for autocomplete UI."""
    return sorted(f"{t} — {n}" for t, n in NSE_TICKERS.items())


def parse_ticker_option(option: str) -> str:
    """Extract the raw ticker from a 'TICKER — Name' autocomplete option."""
    return option.split(" — ")[0].strip()
